-- MySQL Script generated by MySQL Workbench
-- Sun Oct 12 08:06:52 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema burgerDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema burgerDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `burgerDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `burgerDB` ;

-- -----------------------------------------------------
-- Table `burgerDB`.`ComponentType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `burgerDB`.`ComponentType` (
  `type_id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `burgerDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `burgerDB`.`User` (
  `idUser` INT NOT NULL,
  `fName` VARCHAR(45) NULL,
  `lName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `ccProvider` VARCHAR(45) NULL,
  `ccNumber` INT UNSIGNED NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `burgerDB`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `burgerDB`.`Order` (
  `idOrder` VARCHAR(45) NOT NULL,
  `User_idUser` INT NOT NULL,
  `timestamp` INT NULL AUTO_INCREMENT,
  INDEX `fk_Order_User2_idx` (`User_idUser` ASC),
  PRIMARY KEY (`idOrder`),
  CONSTRAINT `fk_Order_User2`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `burgerDB`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `burgerDB`.`Side`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `burgerDB`.`Side` (
  `idSide` INT NOT NULL,
  `sideName` VARCHAR(45) NULL,
  PRIMARY KEY (`idSide`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `burgerDB`.`Burger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `burgerDB`.`Burger` (
  `idBurger` INT NOT NULL,
  `Order_idOrder` VARCHAR(45) NOT NULL,
  `quantity` INT UNSIGNED NULL,
  `Side_idSide` INT NOT NULL,
  PRIMARY KEY (`idBurger`, `Order_idOrder`),
  INDEX `fk_Burger_Order1_idx` (`Order_idOrder` ASC),
  INDEX `fk_Burger_Side1_idx` (`Side_idSide` ASC),
  CONSTRAINT `fk_Burger_Order1`
    FOREIGN KEY (`Order_idOrder`)
    REFERENCES `burgerDB`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Burger_Side1`
    FOREIGN KEY (`Side_idSide`)
    REFERENCES `burgerDB`.`Side` (`idSide`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `burgerDB`.`BurgerComponent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `burgerDB`.`BurgerComponent` (
  `idBurgerComponent` INT NOT NULL,
  `componentName` VARCHAR(45) NULL,
  `componentType` INT NULL,
  PRIMARY KEY (`idBurgerComponent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `burgerDB`.`Burger_has_BurgerComponent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `burgerDB`.`Burger_has_BurgerComponent` (
  `Burger_idBurger` INT NOT NULL,
  `BurgerComponent_idBurgerComponent` INT NOT NULL,
  PRIMARY KEY (`Burger_idBurger`, `BurgerComponent_idBurgerComponent`),
  INDEX `fk_Burger_has_BurgerComponent_BurgerComponent1_idx` (`BurgerComponent_idBurgerComponent` ASC),
  INDEX `fk_Burger_has_BurgerComponent_Burger1_idx` (`Burger_idBurger` ASC),
  CONSTRAINT `fk_Burger_has_BurgerComponent_Burger1`
    FOREIGN KEY (`Burger_idBurger`)
    REFERENCES `burgerDB`.`Burger` (`idBurger`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Burger_has_BurgerComponent_BurgerComponent1`
    FOREIGN KEY (`BurgerComponent_idBurgerComponent`)
    REFERENCES `burgerDB`.`BurgerComponent` (`idBurgerComponent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
