-- MySQL Script generated by MySQL Workbench
-- Thu Oct 16 20:20:39 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ComponentType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ComponentType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ComponentType` (
  `type_id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `fName` VARCHAR(45) NULL,
  `lName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `ccProvider` VARCHAR(45) NULL,
  `ccNumber` VARCHAR(20) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `User_idUser` INT NOT NULL,
  INDEX `fk_Order_User2_idx` (`User_idUser` ASC),
  PRIMARY KEY (`idOrder`),
  CONSTRAINT `fk_Order_User2`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Burger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Burger` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Burger` (
  `idBurger` INT NOT NULL AUTO_INCREMENT,
  `Order_idOrder` VARCHAR(45) NOT NULL,
  `quantity` INT UNSIGNED NULL,
  PRIMARY KEY (`idBurger`, `Order_idOrder`),
  INDEX `fk_Burger_Order1_idx` (`Order_idOrder` ASC),
  CONSTRAINT `fk_Burger_Order1`
    FOREIGN KEY (`Order_idOrder`)
    REFERENCES `mydb`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BurgerComponent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BurgerComponent` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BurgerComponent` (
  `idBurgerComponent` INT NOT NULL AUTO_INCREMENT,
  `componentName` VARCHAR(45) NULL,
  `componentType` INT NULL,
  PRIMARY KEY (`idBurgerComponent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Burger_has_BurgerComponent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Burger_has_BurgerComponent` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Burger_has_BurgerComponent` (
  `Burger_idBurger` INT NOT NULL AUTO_INCREMENT,
  `BurgerComponent_idBurgerComponent` INT NOT NULL,
  PRIMARY KEY (`Burger_idBurger`, `BurgerComponent_idBurgerComponent`),
  INDEX `fk_Burger_has_BurgerComponent_BurgerComponent1_idx` (`BurgerComponent_idBurgerComponent` ASC),
  INDEX `fk_Burger_has_BurgerComponent_Burger1_idx` (`Burger_idBurger` ASC),
  CONSTRAINT `fk_Burger_has_BurgerComponent_Burger1`
    FOREIGN KEY (`Burger_idBurger`)
    REFERENCES `mydb`.`Burger` (`idBurger`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Burger_has_BurgerComponent_BurgerComponent1`
    FOREIGN KEY (`BurgerComponent_idBurgerComponent`)
    REFERENCES `mydb`.`BurgerComponent` (`idBurgerComponent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
